[ifchange]
enabled = true # default: false

[donotland]
enabled = true # default: true

[todo]
enabled = true # default: false

[neveredit]
enabled = true # default: false
paths = []     # default: []

[nocurlyquotes]
enabled = true # default: false
