name: ci
permissions:
  contents: read
"on":
  pull_request: null
  push: null
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
env:
  MISE_EXPERIMENTAL: true
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: apt
        run: sudo apt-get update && sudo apt-get install --no-install-recommends -y build-essential git libyaml-dev node-gyp pkg-config python-is-python3 google-chrome-stable
      - name: checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: mise
        uses: jdx/mise-action@c2a87611a18de5b3828c5652fe268e992400cb5c # v4.3.0
      - uses: pnpm/setup@fbda4c85fc2e1e08721cd8763afea8f48d60f024 # v3.0.0
        # runs pnpm install itself
        with:
          runtime: node@24
          cache: true
      - name: prepare-ci
        run: bin/mise run prepare-ci
      - name: ci:brakeman
        run: bin/mise run ci:brakeman
      - name: ci:rubocop
        run: bin/mise run ci:rubocop
      - name: artifacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        if: failure()
        with:
          name: screenshots
          path: ${{ github.workspace }}/tmp/screenshots
          if-no-files-found: ignore
